### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by adibratul** [bilelomrani1/s5p-tools#1]
`bash: /home/adib/anaconda3/bin/s5p-request: /Users/bilelomrani/miniconda3/envs/s5p-tools/bin/python3: bad interpreter: No such file or directory`

how to solve this ?

**Comment by bilelomrani1** [comment]
It seems like an issue with Conda packaging. I am not satisfied with the current solution anyway so I will refactor the code into a simpler CLI, without packaging.
