### ISSUE TITLE
L3 Resampling and memory usage

### ISSUE THREAD

**Issue by 3zero2** [bilelomrani1/s5p-tools#2]
Is it normal that the HARP tools for the L3 resampling use huge amounts of memory?  It tried to download and process L2__NO2___ data with this command:

`python s5p-request.py L2__NO2___ --date NOW-2HOUR NOW --num-workers 1`

The download was quite small but when it got to the L3 resampling python started to use huge amounts of RAM until it crashed the computer.  Is this expected when using HARP tools?

<img width="825" alt="Screenshot 2021-03-08 at 18 57 36" src="https://user-images.githubusercontent.com/6965396/110361766-c073aa00-8040-11eb-942a-2f918b402522.png">

**Comment by bilelomrani1** [comment]
You did not specify an area of interest in the above command, so by default the script will download and process the NO2 data over the whole globe. The default resolution being 7x4km approximately, this is indeed a huge amount of data to resample. As far as I know, HARP tries to load the whole grid in memory and cannot work in batch.
If you want to resample the data globally, i suggest either:
- lowering the resolution with the `--resolution` option
- splitting the area of interest in multiple smaller chunks

**Comment by 3zero2** [comment]
You are completely right. I provided an --aoi and now it completes.

For those reading this I had to put `import geopandas` on the first line of the s5p_requests file. For some reason if geopandas was not imported first it was. giving off a segmentation fault.
