### ISSUE TITLE
NetCDF coordinates do not match given GeoJSON file

### ISSUE THREAD

**Issue by 3zero2** [bilelomrani1/s5p-tools#7]
I'm running s5p-request with this command:

`python s5p-request.py L2__AER_AI --aoi newmap.geojson --qa 80 --num-workers 1`

The geojson file is this one: [newmap.geojson.zip](https://github.com/bilelomrani1/s5p-tools/files/6798782/newmap.geojson.zip)

The area covered by the geojson is: <img width="639" alt="Screenshot 2021-07-12 at 07 37 01" src="https://user-images.githubusercontent.com/6965396/125236263-f4f3bd00-e2e3-11eb-9869-fe6e7535f780.png">

But the output NetCDF coordinates are: 
![image](https://user-images.githubusercontent.com/6965396/125236342-0f2d9b00-e2e4-11eb-9749-29d78aa97896.png)

I am 99% sure that I'm missing something here rather than this being a bug in the script - however I'm not sure what I'm missing. @bilelomrani1, you have any idea please? Thank you.

**Comment by bilelomrani1** [comment]
There was indeed an unfortunate bug in the bounding box calculation for the resampling operation, which was fixed with 1f6787f. Can you update your scripts and try again?

**Comment by 3zero2** [comment]
Thank you @bilelomrani1 . The issue seems to be fixed.
